name:                lang
version:             0.1.0.0
github:              "atmoPunk/lang"
license:             BSD3
author:              "Dmitriy Ivanov"
maintainer:          "atmopunk@outlook.com"
copyright:           "2021 Dmitriy Ivanov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/atmoPunk/lang#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- parser-combinators

library:
  source-dirs: src

executables:
  lang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lang

tests:
  lang-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lang
    - HUnit
    - tasty
    - tasty-hunit
